/**
 * Robust email parsing and candidate-constrained tracking extraction logic (v2.0.0).
 * Shared by the CloudMailin inbound webhook (inboundEmailHandler.js),
 * Gmail push handler (gmailPushHandler.js), and Gmail historical backfill (gmailBackfill.js).
 */

import carrierSpecs from './carrierSpecs.generated.json' with { type: 'json' };

const REDIRECT_PARAM_NAMES = new Set([
  'url', 'target', 'dest', 'destination', 'redirect', 'redirect_url',
  'link', 'r', 'u', 'to', 'next', 'forward', 'target_url', 'click_url',
  'orig_url', 'uri', 'goto'
]);

/**
 * Attempts to decode a URL component and returns a clean http(s) URL if valid.
 * Handles single and double percent-encoded URLs.
 * @param {string} val
 * @returns {string|null}
 */
function tryDecodeUrl(val) {
  if (!val || typeof val !== 'string') return null;
  let decoded = val.trim();
  try {
    if (/%[0-9A-Fa-f]{2}/.test(decoded)) {
      decoded = decodeURIComponent(decoded);
      if (/%[0-9A-Fa-f]{2}/.test(decoded)) {
        decoded = decodeURIComponent(decoded);
      }
    }
  } catch {}

  if (/^https?:\/\/[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/i.test(decoded)) {
    return decoded;
  }
  return null;
}

/**
 * Unwraps nested or redirect URLs generated by email service providers (SendGrid, Klaviyo, AliExpress, Shein, Amazon).
 * @param {string} url
 * @param {number} [maxDepth=3]
 * @returns {string|null} Unwrapped target URL, or null if no redirect parameter found.
 */
export function unwrapRedirectUrl(url, maxDepth = 3) {
  if (!url || typeof url !== 'string') return null;

  let currentUrl = url.trim();
  let unwrapped = null;

  for (let depth = 0; depth < maxDepth; depth++) {
    try {
      const fullUrl = currentUrl.startsWith('http') ? currentUrl : `https://${currentUrl}`;
      const parsed = new URL(fullUrl);

      let extracted = null;

      // 1. Check known redirect parameter keys
      for (const [key, val] of parsed.searchParams.entries()) {
        const lowerKey = key.toLowerCase();
        if (REDIRECT_PARAM_NAMES.has(lowerKey)) {
          const candidate = tryDecodeUrl(val);
          if (candidate) {
            extracted = candidate;
            break;
          }
        }
      }

      // 2. Fallback: inspect parameter values for embedded http/https
      if (!extracted) {
        for (const [_, val] of parsed.searchParams.entries()) {
          if (/https?%3A|https?:\/\//i.test(val)) {
            const candidate = tryDecodeUrl(val);
            if (candidate) {
              extracted = candidate;
              break;
            }
          }
        }
      }

      if (extracted && extracted !== currentUrl) {
        unwrapped = extracted;
        currentUrl = extracted;
      } else {
        break;
      }
    } catch {
      break;
    }
  }

  return unwrapped;
}

/**
 * Normalizes raw carrier names from Schema.org or courier metadata to Deliveree carrier IDs.
 * @param {string} carrierName
 * @returns {string|null}
 */
export function mapCarrierNameToId(carrierName = '') {
  if (!carrierName || typeof carrierName !== 'string') return null;
  const clean = carrierName.trim().toLowerCase();

  if (/ups|united parcel/i.test(clean)) return 'ups';
  if (/fedex|federal express/i.test(clean)) return 'fedex';
  if (/dhl/i.test(clean)) return 'dhl';
  if (/usps|postal service|united states postal/i.test(clean)) return 'usps';
  if (/israel\s*post|דואר\s*ישראל|postil/i.test(clean)) return 'israel-post';
  if (/cainiao|aliexpress/i.test(clean)) return 'cainiao';
  if (/chita|ציטה|צ'יטה/i.test(clean)) return 'chita';
  if (/hfd|epost|אי-?פוסט/i.test(clean)) return 'hfd';
  if (/boxit|בוקסיט/i.test(clean)) return 'boxit';
  if (/buzzr|באזר/i.test(clean)) return 'buzzr';
  if (/tapuz|תפוז/i.test(clean)) return 'tapuz';
  if (/bar[- ]?distribution|בר\s*הפצה|barexpress/i.test(clean)) return 'bar-distribution';
  if (/lionwheel|ליאון\s*וויל/i.test(clean)) return 'lionwheel';
  if (/yunexpress|yuntrack/i.test(clean)) return 'yunexpress';
  if (/yanwen/i.test(clean)) return 'yanwen';
  if (/royal\s*mail/i.test(clean)) return 'royal-mail';
  if (/aramex/i.test(clean)) return 'aramex';

  return null;
}

/**
 * Recursively traverses parsed JSON-LD objects looking for Schema.org ParcelDelivery,
 * Order, and DeliveryEvent shipments.
 * @param {any} obj
 * @param {Array<object>} results
 * @returns {Array<object>}
 */
function findSchemaOrgShipments(obj, results = []) {
  if (!obj || typeof obj !== 'object') return results;

  if (Array.isArray(obj)) {
    for (const item of obj) {
      findSchemaOrgShipments(item, results);
    }
    return results;
  }

  if (obj['@graph'] && Array.isArray(obj['@graph'])) {
    findSchemaOrgShipments(obj['@graph'], results);
  }

  const type = String(obj['@type'] || '');
  const hasTracking = Boolean(obj.trackingNumber || obj.trackingUrl);

  if (/ParcelDelivery|DeliveryEvent/i.test(type) || hasTracking) {
    const trackingNumber = typeof obj.trackingNumber === 'string'
      ? obj.trackingNumber.trim()
      : (typeof obj.trackingNumber === 'number' ? String(obj.trackingNumber) : '');

    const trackingUrl = typeof obj.trackingUrl === 'string' ? obj.trackingUrl.trim() : '';

    let carrierName = '';
    if (typeof obj.carrier === 'string') {
      carrierName = obj.carrier;
    } else if (obj.carrier && typeof obj.carrier.name === 'string') {
      carrierName = obj.carrier.name;
    } else if (typeof obj.hasDeliveryMethod === 'string') {
      carrierName = obj.hasDeliveryMethod;
    }

    let title = '';
    if (typeof obj.itemShipped === 'string') {
      title = obj.itemShipped;
    } else if (obj.itemShipped && typeof obj.itemShipped.name === 'string') {
      title = obj.itemShipped.name;
    } else if (Array.isArray(obj.itemShipped) && obj.itemShipped[0]?.name) {
      title = obj.itemShipped[0].name;
    }

    let store = '';
    let orderNumber = '';
    if (obj.partOfOrder) {
      orderNumber = obj.partOfOrder.orderNumber || '';
      const merchant = obj.partOfOrder.merchant || obj.partOfOrder.seller;
      if (typeof merchant === 'string') store = merchant;
      else if (merchant?.name) store = merchant.name;
    }

    let status = '';
    const rawStatus = String(obj.deliveryStatus || '');
    if (/Delivered/i.test(rawStatus)) status = 'delivered';
    else if (/InTransit|Dispatched/i.test(rawStatus)) status = 'in_transit';
    else if (/Pickup/i.test(rawStatus)) status = 'ready_for_pickup';

    if (trackingNumber || trackingUrl) {
      results.push({
        trackingNumber,
        trackingUrl,
        carrier: carrierName,
        title,
        store,
        orderNumber,
        status,
        expectedArrivalUntil: obj.expectedArrivalUntil || obj.expectedArrivalFrom || ''
      });
    }
  }

  if (/Order/i.test(type)) {
    const orderNumber = obj.orderNumber || '';
    const merchant = obj.merchant || obj.seller;
    const store = typeof merchant === 'string' ? merchant : (merchant?.name || '');

    if (obj.orderDelivery) {
      const deliveries = Array.isArray(obj.orderDelivery) ? obj.orderDelivery : [obj.orderDelivery];
      for (const del of deliveries) {
        if (del && typeof del === 'object') {
          if (!del.partOfOrder) {
            del.partOfOrder = { orderNumber, merchant: store };
          }
          findSchemaOrgShipments(del, results);
        }
      }
    }
  }

  return results;
}

/**
 * Extracts Schema.org structured data (JSON-LD) from email HTML.
 * @param {string} content Raw HTML or JSON-LD payload
 * @returns {Array<{ trackingNumber: string, trackingUrl: string, carrier: string, title: string, store: string, orderNumber: string, status: string, expectedArrivalUntil: string }>}
 */
export function extractSchemaOrgData(content) {
  if (!content || typeof content !== 'string') return [];

  const results = [];
  const trimmed = content.trim();

  // If payload is already a raw JSON string
  if (trimmed.startsWith('{') || trimmed.startsWith('[')) {
    try {
      const parsed = JSON.parse(trimmed);
      findSchemaOrgShipments(parsed, results);
      if (results.length > 0) return results;
    } catch {}
  }

  // Extract from <script type="application/ld+json"> tags
  const scriptRegex = /<script[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;
  let match;

  while ((match = scriptRegex.exec(content)) !== null) {
    const rawJson = match[1]?.trim();
    if (!rawJson) continue;

    try {
      const parsed = JSON.parse(rawJson);
      findSchemaOrgShipments(parsed, results);
    } catch {
      // Ignore malformed JSON in script tags
    }
  }

  return results;
}

/**
 * Known carrier tracking URL patterns for direct link extraction.
 */
export const CARRIER_URL_PATTERNS = [
  { carrier: 'chita', pattern: /(?:chtr\.co\.il|chita(?:-il)?\.co\.il|chita-il\.com)(?:\/(?:t|runportal\/track|runportal\/tracking|tracking)\/([A-Za-z0-9_-]{6,20})|.*?[?&](?:num|b|track|code)=([A-Za-z0-9_-]{6,20})|\/([A-Za-z0-9_-]{6,20}))/i },
  { carrier: 'hfd', pattern: /(?:hfd\.co\.il|epost\.co\.il|tracking\.hfd\.co\.il)(?:\/(?:t|tracking|track|e)\/([A-Za-z0-9_-]{6,20})|.*?[?&](?:num|t|track|barcode|item|b)=([A-Za-z0-9_-]{6,20}))/i },
  { carrier: 'boxit', pattern: /boxit\.co\.il(?:\/(?:tracking|b|lockers)\/([A-Za-z0-9_-]{6,20})|.*?[?&](?:b|num|code|track)=([A-Za-z0-9_-]{6,20}))/i },
  { carrier: 'buzzr', pattern: /(?:buzzr\.co\.il|link\.buzzr\.co\.il)(?:\/(?:track|tracking|b)\/([A-Za-z0-9_-]{6,20})|.*?[?&](?:num|track|code|b)=([A-Za-z0-9_-]{6,20}))/i },
  { carrier: 'tapuz', pattern: /(?:tapuzdelivery\.co\.il|tapuz\.co\.il)(?:\/(?:track|tracking)\/([A-Za-z0-9_-]{6,20})|.*?[?&](?:num|track|code)=([A-Za-z0-9_-]{6,20}))/i },
  { carrier: 'bar-distribution', pattern: /(?:bardistribution\.co\.il|barexpress\.co\.il|bar-express\.co\.il)(?:\/(?:track|tracking)\/([A-Za-z0-9_-]{6,20})|.*?[?&](?:track|tracknum|num|barcode)=([A-Za-z0-9_-]{6,20}))/i },
  { carrier: 'lionwheel', pattern: /(?:lionwheel\.com|tracking\.lionwheel\.com)(?:\/(?:orders|tracking|track)\/([A-Za-z0-9_-]{6,20})|.*?[?&](?:order|orderId|num|track)=([A-Za-z0-9_-]{6,20}))/i },
  { carrier: 'israel-post', pattern: /(?:mypost\.israelpost\.co\.il|israelpost\.co\.il|postil\.com)(?:\/(?:itemtrace|item|tracking)\/([A-Za-z0-9_-]{8,25})|.*?[?&](?:itemcode|item|barcode|num|track|id)=([A-Za-z0-9_-]{8,25}))/i },
  { carrier: 'dhl', pattern: /dhl\.com\/.*?tracking-id=([A-Za-z0-9_-]{8,25})/i },
  { carrier: 'fedex', pattern: /fedex\.com\/.*?(?:trknbr|tracknumbers)=([0-9]{10,25})/i },
  { carrier: 'ups', pattern: /ups\.com\/.*?tracknum=([0-9A-Za-z]{10,25})/i },
  { carrier: 'cainiao', pattern: /(?:cainiao\.com|global\.cainiao\.com)(?:\/.*?mailNoList=([A-Za-z0-9_-]{8,35})|.*?[?&](?:mailNoList|mailNo|nums|num)=([A-Za-z0-9_-]{8,35}))/i },
  { carrier: 'usps', pattern: /(?:tools\.usps\.com|usps\.com).*?(?:tLabels|tracknum|track)=([A-Za-z0-9_-]{10,35})/i },
  { carrier: 'yunexpress', pattern: /(?:yunexpress\.com|yuntrack\.com).*?(?:pNumbers|num|track)=([A-Za-z0-9_-]{8,35})/i },
  { carrier: 'yanwen', pattern: /(?:yw56\.com\.cn|yanwen\.com\.cn).*?(?:num|nums|track)=([A-Za-z0-9_-]{8,35})/i },
  { carrier: 'royal-mail', pattern: /(?:royalmail\.com).*?(?:track|tracking|num|id)=([A-Za-z0-9_-]{8,35})/i },
  { carrier: 'aramex', pattern: /(?:aramex\.com).*?(?:ShipmentNumber|shipmentNumber|num|track)=([A-Za-z0-9_-]{8,35})/i }
];

/**
 * Extracts tracking number and carrier from a single URL, unwrapping redirects if needed.
 * @param {string} url
 * @returns {{ trackingNumber: string, carrier: string } | null}
 */
export function extractTrackingFromUrl(url) {
  if (!url || typeof url !== 'string') return null;
  const unwrapped = unwrapRedirectUrl(url) || url;

  for (const { carrier, pattern } of CARRIER_URL_PATTERNS) {
    const match = unwrapped.match(pattern);
    const candidateVal = match ? (match[1] || match[2] || match[3]) : null;
    if (candidateVal && !isFalsePositive(candidateVal, unwrapped)) {
      return {
        trackingNumber: candidateVal.trim().toUpperCase(),
        carrier
      };
    }
  }

  try {
    const fullUrl = unwrapped.startsWith('http') ? unwrapped : `https://${unwrapped}`;
    const parsed = new URL(fullUrl);
    const GENERIC_PARAMS = [
      'track', 'tracking', 'num', 'code', 't', 'id', 'barcode', 'item', 'awb', 'b',
      'itemcode', 'mailNoList', 'mailNo', 'trknbr', 'tLabels', 'pNumbers', 'ShipmentNumber', 'tracknum'
    ];
    for (const p of GENERIC_PARAMS) {
      const val = parsed.searchParams.get(p);
      if (val && val.trim().length >= 6 && val.trim().length <= 35 && !isFalsePositive(val, unwrapped)) {
        return {
          trackingNumber: val.trim().toUpperCase(),
          carrier: 'other'
        };
      }
    }
  } catch {}

  return null;
}

/**
 * Strips HTML tags while preserving and extracting embedded hyperlinks and unwrapping redirect URLs.
 * Appends extracted URLs and anchor text so tracking links in buttons/banners are never lost.
 * @param {string} html
 * @returns {string}
 */
export function sanitizeEmailHtml(html) {
  if (typeof html !== 'string') return '';

  // 1. Extract all href links and unwrap ESP redirects
  const linkRegex = /<a\s+(?:[^>]*?\s+)?href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;
  const extractedLinks = [];
  let linkMatch;
  while ((linkMatch = linkRegex.exec(html)) !== null) {
    const href = linkMatch[1];
    const anchorText = linkMatch[2]?.replace(/<[^>]+>/g, '').trim();
    if (href && !href.startsWith('mailto:') && !href.startsWith('javascript:')) {
      const unwrapped = unwrapRedirectUrl(href);
      if (unwrapped) {
        extractedLinks.push(` ${anchorText || ''} ${unwrapped} `);
      }
      extractedLinks.push(` ${anchorText || ''} ${href} `);
    }
  }

  // 2. Remove script and style tags
  let clean = html
    .replace(/<style[^>]*>[\s\S]*?<\/style>/gi, '')
    .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, '');

  // 3. Strip all HTML tags
  clean = clean.replace(/<[^>]+>/g, ' ');

  // 4. Decode common HTML entities
  clean = clean
    .replace(/&nbsp;/gi, ' ')
    .replace(/&amp;/gi, '&')
    .replace(/&lt;/gi, '<')
    .replace(/&gt;/gi, '>')
    .replace(/&quot;/gi, '"')
    .replace(/&#39;/gi, "'")
    .replace(/&zwnj;/gi, '')
    .replace(/&zwj;/gi, '')
    .replace(/\s+/g, ' ')
    .trim();

  // 5. Append extracted links at the end so courier URLs are reachable
  if (extractedLinks.length > 0) {
    clean += ' ' + extractedLinks.join(' ');
  }

  return clean;
}

/**
 * Known store signatures mapped from sender addresses or body signatures.
 */
const STORE_SIGNATURES = [
  { store: 'Amazon', pattern: /amazon\.(com|co\.uk|de|fr|es|it|co\.jp|ca|com\.be)/i },
  { store: 'AliExpress', pattern: /aliexpress(\.com)?/i },
  { store: 'eBay', pattern: /ebay\.(com|co\.uk|de)/i },
  { store: 'SHEIN', pattern: /shein(\.com)?/i },
  { store: 'Temu', pattern: /temu(\.com)?/i },
  { store: 'ASOS', pattern: /asos(\.com)?/i },
  { store: 'iHerb', pattern: /iherb(\.com)?/i },
  { store: 'Zara', pattern: /zara(\.com)?/i },
  { store: 'Next', pattern: /next(direct)?(\.com|\.co\.il)?/i },
  { store: 'KSP', pattern: /ksp(\.co\.il)?/i },
  { store: 'Ivory', pattern: /ivory(\.co\.il)?/i },
  { store: 'Super-Pharm', pattern: /(super-pharm|סופר-?פארם)/i },
  { store: 'Shufersal', pattern: /(shufersal|שופרסל)/i },
  { store: 'Terminal X', pattern: /terminal\s*x/i },
  { store: 'Wolt', pattern: /wolt(\.com)?/i },
  // Anchored on the domain or a word boundary: "bug" is three letters of
  // ordinary English, and unanchored it matched "debug", "bugfix" and any
  // footer that happened to contain the word — filing a Shopify store's
  // shipping mail under an Israeli electronics chain.
  { store: 'Bug', pattern: /\bbug\.co\.il\b|\bbug\b/i },
  { store: 'Castro', pattern: /(castro|קסטרו)/i },
  { store: 'Renuar', pattern: /(renuar|רנואר)/i },
  { store: 'Foot Locker', pattern: /foot\s*locker/i }
];

/**
 * Common false-positive patterns (phone numbers, OTP verification codes, dates, prices, etc.).
 */
const FALSE_POSITIVES = [
  // Israeli phone numbers: 050..., 052..., 053..., 054..., 058..., 9725..., +9725...
  /^(?:\+?972|0)(?:5[0-9]|7[0-9]|[23489])\d{7}$/,
  // ISO Dates (YYYY-MM-DD, DD/MM/YYYY)
  /^(?:\d{4}[-/.]\d{2}[-/.]\d{2}|\d{2}[-/.]\d{2}[-/.]\d{4})$/,
  // Standard Order IDs (e.g. Amazon 114-8291029-1928301)
  /^\d{3}-\d{7}-\d{7}$/,
  // Prices / currency
  /^\d+(?:\.\d{2})?\s*(?:₪|\$|€|ILS|USD|EUR)$/i,
  // Generic numeric words like years or short IDs
  /^(?:202[0-9]|2030)$/
];

export const METADATA_WORDS = new Set([
  'UPDATE', 'UPDATES', 'DETAILS', 'DETAIL', 'STATUS', 'INFO', 'INFORMATION',
  'ALERT', 'ALERTS', 'NOTIFICATION', 'NOTIFICATIONS', 'MESSAGE', 'MESSAGES',
  'NUMBER', 'NUMBERS', 'CODE', 'CODES', 'LINK', 'LINKS', 'ONLINE', 'CENTER',
  'SERVICE', 'SERVICES', 'DELIVERY', 'DELIVERIES', 'SHIPMENT', 'SHIPMENTS',
  'PACKAGE', 'PACKAGES', 'PARCEL', 'PARCELS', 'TRACK', 'TRACKING', 'REPORT',
  'SUMMARY', 'CUSTOMER', 'SUPPORT', 'CONFIRMATION', 'RECEIPT', 'PORTAL', 'LOGISTICS',
  'CARRIER', 'CARRIERS', 'DEVELOPER', 'DEVELOPERS', 'ACCOUNT', 'INVOICE', 'BILLING'
]);

export const PROMOTIONAL_MARKERS = [
  /מבצע/, /הנחה/, /קופון/, /בתוקף\s*עד/, /קנו\s*עכשיו/, /הצטרפו/, /להסרה/,
  /דרגו\s*אותנו/, /סקר/, /שביעות\s*רצון/, /איך\s*היה\s*השירות/, /נשמח\s*למשוב/,
  /\bcoupon\b/i, /\bpromo\b/i, /\bdiscount\b/i, /\b\d{1,2}%\s*off\b/i,
  /\bsale\b/i, /\bunsubscribe\b/i, /\bsurvey\b/i, /\brate\s+(?:us|your)\b/i,
  /\bshop\s+now\b/i, /\blimited\s+time\b/i, /\bdear\s+developer\b/i,
  /\btracking\s+api\b/i, /\ball-in-one\s+package\s+tracking\b/i,
  /\bsupported\s+carriers\b/i
];

export function isPromotionalContext(text = '') {
  if (!text || typeof text !== 'string') return false;
  return PROMOTIONAL_MARKERS.some((marker) => marker.test(text));
}

/**
 * Compiled rules from generated spec.
 */
const COMPILED_RULES = (carrierSpecs.rules || []).map((r) => ({
  ...r,
  re: new RegExp(r.source, r.flags)
}));

/**
 * Standard UPU S10 Modulo-11 Checksum (Israel Post, Cainiao S10, USPS S10, Royal Mail S10).
 * @param {string} s10Identifier
 * @returns {boolean}
 */
export function validateUPUS10Mod11(s10Identifier) {
  if (!s10Identifier || typeof s10Identifier !== 'string') return false;
  const clean = s10Identifier.trim().toUpperCase();
  if (!/^[A-Z]{2}\d{9}[A-Z]{2}$/.test(clean)) return false;

  const weights = [8, 6, 4, 2, 3, 5, 9, 7];
  const digits = clean.slice(2, 10);
  const checkDigit = parseInt(clean[10], 10);

  let sum = 0;
  for (let i = 0; i < 8; i++) {
    sum += parseInt(digits[i], 10) * weights[i];
  }

  const remainder = sum % 11;
  let calculatedCheck = 11 - remainder;

  if (calculatedCheck === 10) {
    calculatedCheck = 0;
  } else if (calculatedCheck === 11) {
    calculatedCheck = 5;
  }

  return calculatedCheck === checkDigit;
}

/**
 * USPS IMpb weighted modulo-10 checksum (weights alternate 3, 1 from the
 * right-most data digit). The final digit is the check digit.
 *
 * This intentionally mirrors the client-side `validateMod10(value, [3, 1])`
 * implementation without importing client code into the Functions deploy.
 * @param {string} value
 * @returns {boolean}
 */
export function validateMod10(value) {
  if (!value || typeof value !== 'string' || !/^\d+$/.test(value) || value.length < 2) {
    return false;
  }

  let sum = 0;
  let weight = 3;
  for (let index = value.length - 2; index >= 0; index -= 1) {
    sum += Number(value[index]) * weight;
    weight = weight === 3 ? 1 : 3;
  }

  return (10 - (sum % 10)) % 10 === Number(value[value.length - 1]);
}

/**
 * Evaluates a checksum algorithm named by the generated carrier spec.
 * @param {string} value
 * @param {string} checksumAlgorithm
 * @returns {'pass' | 'fail' | 'not-applicable'}
 */
function evaluateChecksum(value, checksumAlgorithm) {
  if (checksumAlgorithm === 'upu-s10') {
    return validateUPUS10Mod11(value) ? 'pass' : 'fail';
  }
  if (checksumAlgorithm === 'mod10-31') {
    return validateMod10(value) ? 'pass' : 'fail';
  }
  return 'not-applicable';
}

/**
 * Checks if a string is a false-positive tracking candidate.
 * @param {string} candidate
 * @param {string} [context='']
 * @returns {boolean}
 */
export function isFalsePositive(candidate, context = '') {
  if (!candidate || candidate.length < 5 || candidate.length > 45) return true;
  const trimmed = candidate.trim();
  if (METADATA_WORDS.has(trimmed.toUpperCase())) return true;
  if (FALSE_POSITIVES.some((re) => re.test(trimmed))) return true;
  const clean = trimmed.replace(/[\s-]/g, '');
  if (METADATA_WORDS.has(clean.toUpperCase())) return true;
  if (FALSE_POSITIVES.some((re) => re.test(clean))) return true;

  // Real tracking numbers ALWAYS contain at least one digit
  if (!/\d/.test(clean)) return true;

  // OTP Verification Code Guard: 4-8 digits immediately next to verification keywords
  if (/^\d{4,8}$/.test(clean) && context) {
    if (/(?:קוד\s*אימות|קוד\s*חד-?פעמי|אימות\s*חשבון|verification\s*code|one-?time\s*password|otp|security\s*code)/i.test(context)) {
      return true;
    }
  }

  return false;
}

/**
 * Extracts store name from sender email or text.
 * @param {string} from
 * @param {string} text
 * @returns {string|null}
 */
function matchStoreSignature(value = '') {
  if (!value) return null;
  for (const { store, pattern } of STORE_SIGNATURES) {
    if (pattern.test(value)) return store;
  }
  return null;
}

export function detectStore(from = '', text = '') {
  // The sender is evidence; the body is a guess. Scanning both at once, as
  // this did, let any word in a footer outrank the address the mail actually
  // came from — a "bug" in SEESTARZ's markup made the package a BUG order.
  return matchStoreSignature(from) || matchStoreSignature(text);
}

/**
 * The store name to show the user, which is a different question from
 * `detectStore`'s.
 *
 * `detectStore` answers "is this one of the merchants we recognise", and
 * callers use that as a gate — extractOrderStatusDetails will not invent a
 * card for a message it cannot attribute. Widening it to always return
 * something removes that gate and turns every shipping-ish email into a card.
 *
 * This answers the softer question "what should the card say". An unrecognised
 * sender still names itself: SEESTARZ is a store the signature list will never
 * contain, and its own display name beats "Online Order".
 *
 * @param {string} from
 * @param {string} text
 * @returns {string} '' when there is nothing worth showing
 */
export function resolveStoreName(from = '', text = '') {
  // Strictly in order of how much the signal is worth. A recognised sender is
  // best; the sender's own name is next and beats anything the body claims;
  // scanning the body is the last resort, and the only step that can be
  // fooled by a word in a footer.
  return matchStoreSignature(from)
    || senderDisplayName(from)
    || matchStoreSignature(text)
    || '';
}

/**
 * The human-facing name of an email sender, or '' when there isn't one worth
 * showing. Prefers the display name, falls back to the mailbox domain with
 * its public suffix and any no-reply-style subdomain removed.
 *
 * @param {string} from A From header, e.g. 'SEESTARZ <noreply@seestarz.com>'
 * @returns {string}
 */
export function senderDisplayName(from = '') {
  if (!from || typeof from !== 'string') return '';

  const display = from.match(/^\s*"?([^"<]+?)"?\s*</);
  if (display && display[1]) {
    const name = display[1].trim();
    // A display name that is just the address again tells the user nothing.
    if (name && !name.includes('@') && name.length <= 60) return name;
  }

  const address = (from.match(/[\w.+-]+@([\w.-]+)/) || [])[1];
  if (!address) return '';

  const host = address.toLowerCase()
    .replace(/^(?:mail|email|no-?reply|noreply|info|notifications?|shop|store|news|updates?)\./, '');
  const label = host.split('.')[0];
  if (!label || label.length < 2 || label.length > 40) return '';
  return label.charAt(0).toUpperCase() + label.slice(1);
}

/**
 * Matches an explicit package lifecycle signal in email subject/body text, or
 * null when nothing matched. Shared by `inferDeliveryStatus` (which defaults
 * to 'ordered' for a normal package) and `extractOrderStatusDetails` (which
 * needs to tell "no signal at all" apart from "ordered").
 * @param {string} subject
 * @param {string} body
 * @returns {'in_transit' | 'out_for_delivery' | 'ready_for_pickup' | 'delivered' | 'exception' | null}
 */
function matchDeliveryStatus(subject = '', body = '') {
  const combined = `${subject} ${body}`.toLowerCase();

  // 1. Delivered
  if (
    /\b(delivered|successfully delivered|package delivered|item delivered)\b/i.test(combined) ||
    /(?:נמסרה בהצלחה|נמסר ליעד|החבילה נמסרה|נמסר בהצלחה)/i.test(combined)
  ) {
    return 'delivered';
  }

  // 2. Ready for Pickup / Locker / Collection point
  if (
    /\b(ready for (?:pickup|collection)|available for (?:pickup|collection)|waiting for (?:pickup|collection)|arrived at (?:pickup|collection) point|delivered to locker|ready to collect)\b/i.test(combined) ||
    /(?:מוכנה לאיסוף|ממתינה לאיסוף|הגיעה לנקודת איסוף|הגיעה לנקודת חלוקה|הגיעה ללוקר|הגיע ללוקר|החבילה ממתינה לך|מחכה לך בנקודת|איסוף עצמי מ)/i.test(combined)
  ) {
    return 'ready_for_pickup';
  }

  // 3. Out for delivery (courier on the road)
  if (
    /\b(out for delivery|with (?:the\s+)?courier|on its way to you today|delivery today|arriving today)\b/i.test(combined) ||
    /(?:יוצאת למסירה|יצאה עם שליח|נמסרה לשליח|השליח בדרך אליך|חלוקה היום|מגיע היום)/i.test(combined)
  ) {
    return 'out_for_delivery';
  }

  // 4. Exception / Customs issue
  if (
    /\b(delivery issue|delivery failed|delivery exception|customs clearance required|undeliverable)\b/i.test(combined) ||
    /(?:עיכוב במכס|בעיה במסירה|מסירה נכשלה|נכשל ניסיון מסירה)/i.test(combined)
  ) {
    return 'exception';
  }

  // 5. In Transit / Shipped
  if (
    /\b(shipped|in transit|dispatched|on its way|departed|in delivery)\b/i.test(combined) ||
    /(?:נשלחה|נשלח|בדרך|נמסרה לחברת השליחויות|יצאה לדרך)/i.test(combined)
  ) {
    return 'in_transit';
  }

  return null;
}

/**
 * Infers the package lifecycle status from email subject and body text.
 * @param {string} subject
 * @param {string} body
 * @returns {'ordered' | 'in_transit' | 'out_for_delivery' | 'ready_for_pickup' | 'delivered' | 'exception'}
 */
export function inferDeliveryStatus(subject = '', body = '') {
  return matchDeliveryStatus(subject, body) || 'ordered';
}

export const STATUS_RANK = Object.freeze({
  ordered: 0,
  shipped: 1,
  in_transit: 2,
  customs: 3,
  out_for_delivery: 4,
  ready_for_pickup: 5,
  delivered: 6
});

/**
 * Determines whether a lifecycle status transition is an advancement.
 * Prevents regressions (e.g. an ambiguous email downgrading ready_for_pickup back to ordered).
 * Exception states can be triggered from any active state, and can resolve to out_for_delivery, ready_for_pickup, or delivered.
 *
 * @param {string} [currentStatus]
 * @param {string} [newStatus]
 * @returns {boolean}
 */
export function shouldAdvanceStatus(currentStatus = 'ordered', newStatus = 'ordered') {
  if (!newStatus || currentStatus === newStatus) return false;
  if (currentStatus === 'delivered') return false; // terminal delivery state

  if (newStatus === 'exception') return true;
  if (currentStatus === 'exception') {
    return newStatus === 'out_for_delivery' || newStatus === 'ready_for_pickup' || newStatus === 'delivered';
  }

  const currentRank = STATUS_RANK[currentStatus] ?? -1;
  const newRank = STATUS_RANK[newStatus] ?? -1;

  if (currentRank === -1 || newRank === -1) return false;

  return newRank > currentRank;
}

/**
 * Extracts an order-status signal from an email that names a known store but
 * carries no verifiable carrier tracking number — e.g. a marketplace order
 * number like AliExpress's, which means nothing to any carrier. This is
 * deliberately a lower bar than a tracking-number candidate: a known store
 * plus an explicit lifecycle phrase ("shipped", "out for delivery", ...) is
 * good enough to say *something* happened, but nowhere near good enough to
 * claim carrier-verified tracking, so callers must keep this result visually
 * and structurally distinct from a real trackingNumber-based package.
 *
 * Deliberately requires an explicit status match (not just a known store) —
 * a store's marketing/newsletter mail matching only on sender domain would
 * otherwise spam a package into existence for every promotional email.
 *
 * @param {string} subject
 * @param {string} body
 * @param {string} [from]
 * @returns {{ store: string, status: string, title: string } | null}
 */
export function extractOrderStatusDetails(subject = '', body = '', from = '') {
  const cleanBody = sanitizeEmailHtml(body);
  const combinedText = `${subject} ${cleanBody} ${from}`.slice(0, 25000);
  // Gate on the strict answer — an email we cannot attribute to a recognised
  // merchant must not conjure a card — but show the resolved one, so a
  // recognised-by-body-only match does not put a footer's stray word on the
  // card as the shop's name.
  const store = detectStore(from, combinedText);
  if (!store) return null;
  const displayStore = resolveStoreName(from, combinedText) || store;

  const status = matchDeliveryStatus(subject, cleanBody);
  if (!status) return null;

  const orderNumber = extractOrderNumberFromText(combinedText);

  return {
    store: displayStore,
    status,
    title: generateCleanTitle(subject, displayStore, 'other'),
    ...(orderNumber ? { orderNumber } : {})
  };
}

/**
 * The name of the thing being shipped, taken from the email's own list of
 * contents.
 *
 * Shipping mail routinely states this outright — "Items in this shipment /
 * Rosewater Cream Blouse × 1" — while the subject carries only the order
 * number. generateCleanTitle sees only the subject, and shreds it: "Shipping
 * update for order 469417" came out as "update for", which is what the user
 * ends up reading on the card.
 *
 * Takes the first item and no more. A multi-item shipment gets the first
 * product rather than a truncated concatenation of all of them, which reads
 * better on a card and is what the package is most likely remembered as.
 *
 * @param {string} body Plain-text email body
 * @returns {string} '' when the email lists no contents
 */
export function extractShippedItemName(body = '') {
  if (!body || typeof body !== 'string') return '';

  const heading = /(?:items?\s+(?:in\s+)?(?:this\s+)?(?:shipment|order|package)|items?\s+shipped|what'?s\s+in\s+(?:this\s+)?(?:box|shipment)|הפריטים?\s+במשלוח|פריטים?\s+שנשלחו)/i;
  const match = heading.exec(body);
  if (!match) return '';

  const after = body.slice(match.index + match[0].length, match.index + match[0].length + 400);

  // Newlines cannot be relied on: sanitizeEmailHtml collapses the message to a
  // single line, so the same email arrives here as separate lines from the
  // plain-text part and as one run of text from the HTML one. The quantity
  // marker is the delimiter that survives both — "Rosewater Cream Blouse × 1"
  // ends the name whether or not a newline follows it.
  const candidates = [];
  for (const line of after.split(/\r?\n/)) {
    const quantityCut = line.match(/^(.{3,80}?)\s*[×xX*]\s*\d+/);
    if (quantityCut) candidates.push(quantityCut[1]);
    candidates.push(line);
  }

  for (const raw of candidates) {
    const name = String(raw || '').replace(/\s*[×xX*]\s*\d+\s*$/, '').trim();

    // A size, colour or SKU standing alone is not the product name.
    if (name.length < 3 || name.length > 80) continue;
    if (!/[A-Za-z\u0590-\u05FF]/.test(name)) continue;
    if (/^(?:size|color|colour|qty|quantity|sku|מידה|צבע|כמות)\b/i.test(name)) continue;

    return name;
  }

  return '';
}

/**
 * Derives a clean, user-friendly package title from store and subject.
 * @param {string} subject
 * @param {string|null} store
 * @param {string} carrier
 * @returns {string}
 */
export function generateCleanTitle(subject = '', store = null, carrier = 'other') {
  if (!subject || typeof subject !== 'string') {
    if (store) return `${store} Order`;
    if (carrier !== 'other') return `Package via ${carrier.toUpperCase()}`;
    return 'Online Order';
  }

  // 1. Check for product enclosed in quotes first: e.g. Your order for "Mechanical Keyboard" has shipped
  const productInQuotes = subject.match(/["'״”]([^"'״”]{3,60})["'״”]/);
  if (productInQuotes && productInQuotes[1]) {
    const item = productInQuotes[1].trim();
    if (!/^[A-Z0-9_-]{8,35}$/i.test(item) && !/^(?:order|package|tracking|delivery|shipment)/i.test(item)) {
      return store ? `${store} - ${item}` : item;
    }
  }

  // 2. Check for "for <Item Name>" pattern: e.g. "Delivery update for Running Shoes"
  const forProductMatch = subject.match(/(?:for|עבור)\s+([A-Za-z0-9\u0590-\u05FF\s-]{3,40})(?:\s+(?:has|is|was|נשלח|הגיע|בדרך)|$)/i);
  if (forProductMatch && forProductMatch[1]) {
    const itemCandidate = forProductMatch[1].trim();
    if (!/^(?:order|package|delivery|shipment|pickup|collection|חבילה|משלוח|הזמנה|איסוף|your\s+package)/i.test(itemCandidate) && itemCandidate.length >= 3) {
      return store ? `${store} - ${itemCandidate}` : itemCandidate;
    }
  }

  let clean = subject
    // Strip email forwards / replies
    .replace(/^(?:fwd|fw|re|הועבר|תגובה):\s*/gi, '')
    // Strip common store prefixes like "AliExpress - ", "Amazon.com: ", "SHEIN: "
    .replace(/^(?:aliexpress|amazon(?:\.com)?|shein|temu|ebay|zara|asos|ksp|ivory|super-pharm|wolt)\s*[-:|–—]\s*/gi, '')
    // Strip delivery issue phrases
    .replace(/delivery\s*issue(?:\s*for)?/gi, '')
    // Strip "Package <TRACKING_ID>" or "חבילה <TRACKING_ID>"
    .replace(/(?:package|shipment|order|חבילה|משלוח|הזמנה)\s+[A-Za-z0-9_-]{5,35}/gi, '')
    // Strip tracking numbers
    .replace(/\b[A-Za-z0-9_-]{8,35}\b/g, '')
    // Strip delivery status sentences / phrases
    .replace(/(?:is\s+)?(?:ready|available|waiting)\s+for\s+(?:pickup|collection|delivery)/gi, '')
    .replace(/(?:your\s+order\s+has\s+shipped|order\s+confirmation|shipping\s+confirmation|shipment\s+update|update\s+on\s+order|is\s+on\s+its\s+way|has\s+been\s+dispatched|has\s+been\s+delivered|out\s+for\s+delivery)/gi, '')
    .replace(/(?:נשלחה\s+חבילה|אישור\s+הזמנה|ההזמנה\s+שלך\s+נשלחה|ההזמנה\s+בדרך|החבילה\s+שלך\s+בדרך|הודעה\s+על\s+הגעת\s+חבילה|ממתינה\s+לאיסוף|מוכנה\s+לאיסוף|איסוף\s+מלוקר|איסוף\s+מנקודה|אי-פוסט|שליחויות)/gi, '')
    // Strip remaining generic delivery keywords
    .replace(/\b(?:package|shipment|order|delivery|pickup|collection|delivered|shipped|tracking|item)\b/gi, '')
    .replace(/(?:חבילה|משלוח|הזמנה|איסוף|לוקר|דואר|נקודת\s*חלוקה)/g, '')
    // Strip carrier suffixes like "מ-HFD" or "from HFD" or "via Chita"
    .replace(/(?:מ-|from\s+|via\s+|ב-)(?:hfd|chita|boxit|buzzr|tapuz|bar|lionwheel|israel\s*post|dhl|fedex|ups)/gi, '')
    // Strip punctuation
    .replace(/[#[\](){}:|–—.,/\\-]/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();

  // If the remaining clean text is generic, too short (<3 chars), or purely digits/symbols
  const isGeneric = !clean || 
    clean.length < 3 || 
    /^[0-9_-]+$/.test(clean) ||
    /^(?:package|order|delivery|pickup|collection|delivered|shipped|tracking|item|חבילה|משלוח|הזמנה|איסוף|דואר)$/i.test(clean);

  if (!isGeneric) {
    if (store && !clean.toLowerCase().includes(store.toLowerCase())) {
      return `${store} - ${clean.slice(0, 60)}`.trim();
    }
    return clean.slice(0, 70);
  }

  if (store) return `${store} Order`;
  if (carrier !== 'other') return `Package via ${carrier.toUpperCase()}`;
  return 'Online Order';
}

/**
 * Extracts locker PIN if present in message body.
 * @param {string} text
 * @returns {string|null}
 */
export function extractLockerPin(text = '') {
  if (!text) return null;
  const pinMatch = text.match(/(?:קוד\s*איסוף|קוד\s*לוקר|קוד\s*פתיחה|locker\s*pin|pickup\s*code|collection\s*pin)[\s:=#-]+(\d{4,8})/i);
  return pinMatch ? pinMatch[1] : null;
}

/**
 * Extracts shelf number (מדף) if present in message body.
 * @param {string} text
 * @returns {string|null}
 */
export function extractShelfNumber(text = '') {
  if (!text || typeof text !== 'string') return null;
  const patterns = [
    /(?:(?:מספר\s+|מס['׳]?\s+)?(?:ב)?מדף(?:\s*(?:מספר|מס['׳]?))?)[\s:#*-]+([א-ת0-9]{1,4}(?:[/-][א-ת0-9]{1,4})?|[א-ת]?\d{1,4}[א-ת]?)(?:[^\S\r\n]|$|[.,;!])/i,
    /(?:\b(?:shelf|bin)\s*(?:number|no|num|#)?)[\s:#*-]+([a-z0-9]{1,4}(?:-[a-z0-9]{1,4})?|[a-z]?\d{1,4}[a-z]?)(?:[^\S\r\n]|$|[.,;!])/i
  ];
  for (const pattern of patterns) {
    const match = pattern.exec(text);
    if (match && match[1]) {
      const shelf = match[1].trim();
      if (shelf && !/^(?:http|https|null|undefined)$/i.test(shelf)) {
        return shelf;
      }
    }
  }
  return null;
}

/**
 * Extracts pickup location or locker info from Hebrew and English SMS/Email text snippets.
 * @param {string} text 
 * @returns {string}
 */
export function extractPickupLocation(text = '') {
  if (!text || typeof text !== 'string') return '';

  const patterns = [
    /(?:נקודת\s*איסוף|בנקודת\s*איסוף|נקודת\s*מסירה|בנקודת\s*מסירה|מרכז\s*מסירה|במרכז\s*מסירה|בלוקר|לוקר|ביחידת\s*(?:ה)?דואר|יחידת\s*(?:ה)?דואר|בסוכנות\s*(?:ה)?דואר|סוכנות\s*(?:ה)?דואר|בסניף\s*מסירה|סניף\s*מסירה|בסניף|סניף|בכתובת|כתובת\s*לאיסוף|בחנות|בבית\s*עסק|נקודת\s*חלוקה|בנקודת\s*חלוקה|איסוף\s*מ|מחכה\s*לך\s*ב|ממתינה\s*לך\s*ב|נמצאת\s*ב)[\s:-]+([^,.\r\n]{2,60})/i,
    /(?:waiting\s+(?:for\s+you\s+)?at\s+(?:the\s+)?(?:pickup\s+point|locker|branch)|at\s+(?:the\s+)?pickup\s+point|at\s+(?:the\s+)?locker|at\s+(?:the\s+)?branch|pickup\s+location|pickup\s+point|locker\s+location|waiting\s+(?:for\s+you\s+)?at)[\s:-]+([^,.\r\n]{2,60})/i
  ];

  for (const pattern of patterns) {
    const match = pattern.exec(text);
    if (match && match[1]) {
      let loc = match[1].trim();
      loc = loc.replace(/^(?:(?:at\s+)?(?:the\s+)?(?:pickup\s+point|pickup\s+location|locker|branch)[\s:-]*)+/i, '');
      loc = loc.replace(/(?:\s*[-–—|/.]?\s*(?:שעות\s*פתיחה|שעות\s*פעילות|קוד\s*איסוף|קוד\s*לאיסוף|קוד|טלפון|טל|בירורים|לינק|כתובת|הוראות|phone|tel|hours|open\s+until|open|pin|code|http|https).*)$/i, '');
      loc = loc.replace(/^['":\-–—\s]+|['":\-–—\s]+$/g, '');
      if (loc && loc.length >= 2 && !/^(?:http|https|www|israelpost|hfd|boxit|chita|buzzr)$/i.test(loc)) {
        return loc;
      }
    }
  }

  return '';
}

/**
 * Extracts opening hours string from raw courier SMS or email text.
 * @param {string} text
 * @returns {string} Extracted hours string or empty
 */
export function extractOpeningHours(text = '') {
  if (!text || typeof text !== 'string') return '';

  const patterns = [
    /\b(24\/7(?:\s*\([^)]+\))?|תמיד\s*פתוח|פתוח\s*24\s*שעות)\b/i,
    /(?:שעות\s*פתיחה|שעות\s*פעילות|שעות\s*מסירה|שעות\s*קבלת\s*קהל|זמני\s*פתיחה)[\s:-]+([^\r\n,;.]+(?:,[^\r\n,;.]+)?)/i,
    /(?:opening\s*hours|business\s*hours|hours\s*of\s*operation)[\s:-]+([^\r\n,;.]+(?:,[^\r\n,;.]+)?)/i,
    /\bhours[\s:-]+([^\r\n,;.]+(?:,[^\r\n,;.]+)?)/i
  ];

  for (const pattern of patterns) {
    const match = pattern.exec(text);
    if (match) {
      const raw = match[1] || match[0];
      let cleaned = raw.trim().slice(0, 200);
      cleaned = cleaned.replace(/(?:\s*[-–—|/.]?\s*(?:טלפון|טל|נייד|phone|tel|קוד|איסוף|כתובת|בירורים|לינק|דואר|http|https).*)$/i, '');
      cleaned = cleaned.replace(/^['":\-–—.\s]+|['":\-–—.\s]+$/g, '');
      if (cleaned && cleaned.length >= 4 && !/^(?:http|https|www)$/i.test(cleaned)) {
        return cleaned;
      }
    }
  }

  return '';
}

/**
 * Extracts a store, courier, or pickup contact phone number from text.
 * Handles Israeli landline formats (02/03/04/08/09-XXXXXXX), mobile (05X-XXXXXXX),
 * VoIP/special (07X-XXXXXXX, 1-700/1-800), and international (+972...).
 * @param {string} text
 * @returns {string}
 */
export function extractPickupPhone(text = '') {
  if (!text || typeof text !== 'string') return '';

  const patterns = [
    /(?:טלפון(?:\s*לבירורים|\s*ליצירת\s*קשר|\s*סניף|\s*חנות)?|טל['׳]|נייד|שליח\s*בטלפון|בירורים(?:\s*במוקד)?|מוקד|phone|tel|call)[\s:-]+(\+?972[- ]?[0-9]{1,2}[- ]?[0-9]{3}[- ]?[0-9]{4}|0[2-9][- ]?[0-9]{7}|05[0-9][- ]?[0-9]{7}|1-[78]00[- ]?[0-9]{3}[- ]?[0-9]{3})\b/i,
    /(?:\+972[- ]?[2-9][- ]?[0-9]{7}|0[23489][- ]?[0-9]{7}|05[0-9][- ]?[0-9]{7}|1-[78]00[- ]?[0-9]{3}[- ]?[0-9]{3})\b/
  ];

  for (const pattern of patterns) {
    const match = pattern.exec(text);
    if (match && match[1]) {
      const phone = match[1].trim().replace(/[^\d+]/g, '');
      if (phone.length >= 7 && phone.length <= 15) {
        return match[1].trim();
      }
    } else if (match && match[0]) {
      const phone = match[0].trim().replace(/[^\d+]/g, '');
      if (phone.length >= 7 && phone.length <= 15) {
        return match[0].trim();
      }
    }
  }

  return '';
}

/**
 * Detects whether a delivery was rerouted / redirected to an alternate pickup point.
 * Extracts the redirect flag, reason, and original location if mentioned.
 * @param {string} text
 * @returns {{ isRedirected: boolean, originalPickupLocation?: string, redirectReason?: string, newPickupLocation?: string }}
 */
export function extractRedirectInfo(text = '') {
  if (!text || typeof text !== 'string') return { isRedirected: false };

  const prefixRedirectMatch = /(?:בשל|עקב)\s*(?:עומס|ביקוש|תפוסה|סגירה|תקלה|אילוץ\s*תפעולי)\s*(?:בלוקר|בסניף|בנקודת\s*איסוף|ב)?\s*([^,.\r\n]+?)\s*,\s*(?:(?:החבילה|חבילתך|המשלוח|משלוח)\s*[A-Za-z0-9_-]*\s*)?(?:הועברה|הופנתה|נותבה|נשלחה)\s*(?:ל|אל)?\s*(?:נקודת\s*איסוף|סניף|לוקר|חנות)?[\s:-]+([^,.\r\n]{2,60})/i.exec(text);
  if (prefixRedirectMatch && prefixRedirectMatch[1] && prefixRedirectMatch[2]) {
    let origLoc = prefixRedirectMatch[1].trim().replace(/^['":\-–—\s()]+|['":\-–—\s()]+$/g, '');
    origLoc = origLoc.replace(/^(?:לוקר|סניף|נקודת\s*איסוף)\s*/i, '');
    let newLoc = prefixRedirectMatch[2].trim().replace(/(?:\s*[-–—|/]?\s*(?:שעות\s*פתיחה|קוד\s*איסוף|קוד|שעות\s*פעילות|טלפון|phone|hours).*)$/i, '').replace(/^['":\-–—\s()]+|['":\-–—\s()]+$/g, '');
    return {
      isRedirected: true,
      newPickupLocation: newLoc,
      originalPickupLocation: origLoc || undefined,
      redirectReason: /(?:עומס|capacity|overflow)/i.test(text) ? 'locker_capacity' : 'operational'
    };
  }

  const redirectPatterns = [
    /(?:עקב|בשל)\s*(?:עומס|ביקוש|תפוסה|סגירה|תקלה|אילוץ\s*תפעולי)[^.\r\n]*?(?:הועברה|הופנתה|נותבה|נשלחה)\s*(?:ל|אל)?\s*(?:נקודת\s*איסוף|סניף|לוקר|חנות)?[\s:-]+([^,.\r\n]{2,60})/i,
    /(?:נקודת\s*(?:ה)?איסוף\s*(?:שונתה|הוחלפה|עודכנה)\s*(?:ל|אל)?[\s:-]+)([^,.\r\n]{2,60})/i,
    /(?:הועברה\s*לנקודת\s*איסוף\s*חלופית[\s:-]+)([^,.\r\n]{2,60})/i,
    /(?:חבילתך\s*הועברה\s*(?:ל|אל)?\s*(?:נקודת\s*איסוף|סניף|לוקר)?[\s:-]+)([^,.\r\n]{2,60})/i,
    /(?:(?:redirected|rerouted|transferred)\s+(?:to\s+(?:pickup\s+(?:point|location)|locker|branch)?|at)[\s:-]+)([^,.\r\n]{2,60})/i,
    /(?:pickup\s+(?:point|location)\s+(?:changed|redirected|updated)\s+to[\s:-]+)([^,.\r\n]{2,60})/i
  ];

  for (const pattern of redirectPatterns) {
    const match = pattern.exec(text);
    if (match && match[1]) {
      let newLoc = match[1].trim();
      newLoc = newLoc.replace(/(?:\s*\(?(?:במקום|במקור|instead\s+of).*\)?)$/i, '');
      newLoc = newLoc.replace(/(?:\s*[-–—|/]?\s*(?:שעות\s*פתיחה|קוד\s*איסוף|שעות\s*פעילות|טלפון|phone|hours).*)$/i, '');
      newLoc = newLoc.replace(/^['":\-–—\s()]+|['":\-–—\s()]+$/g, '');

      let origLoc = '';
      const origMatch = /(?:במקום|במקור|originally|instead\s+of)[\s:-]+([^,.)\r\n]{2,60})/i.exec(text);
      if (origMatch && origMatch[1]) {
        origLoc = origMatch[1].trim().replace(/^['":\-–—\s()]+|['":\-–—\s()]+$/g, '');
      }

      return {
        isRedirected: true,
        newPickupLocation: newLoc,
        originalPickupLocation: origLoc || undefined,
        redirectReason: /(?:עומס|capacity|overflow)/i.test(text) ? 'locker_capacity' : 'operational'
      };
    }
  }

  if (/(?:הועברה\s*לנקודת\s*איסוף\s*חלופית|עקב\s*עומס\s*בלוקר|שונתה\s*נקודת\s*האיסוף|package\s*redirected|was\s*redirected|rerouted\s*to\s*alternate)/i.test(text)) {
    return {
      isRedirected: true,
      redirectReason: /(?:עומס|capacity|overflow)/i.test(text) ? 'locker_capacity' : 'operational'
    };
  }

  return { isRedirected: false };
}

function extractOrderNumberFromText(text = '') {
  if (!text) return undefined;
  const match = text.match(/(?:order\s*(?:id|#|no|number)?|מספר\s*הזמנה|הזמנה\s*(?:מס|מספר|מס׳|מס'))\s*[:：#]?\s*([A-Za-z0-9-]{6,35})\b/i);
  if (!match) return undefined;
  const cand = match[1].trim();
  if (cand.length < 6) return undefined;
  if (/^(?:19|20)\d{6,}$/.test(cand)) return undefined;
  return cand;
}

/**
 * Extracts tracking details and ranked candidates from email with multi-signal evidence scoring.
 * Backwards-compatible with all existing callers while exposing v2.0.0 additive fields.
 *
 * @param {string} subject
 * @param {string} body
 * @param {string} [from]
 * @param {object} [options]
 * @returns {object}
 */
export function extractTrackingDetails(subject = '', body = '', from = '', options = {}) {
  const startTime = Date.now();
  const htmlContent = options.html || (/<script|<html|<div|<a\s+/i.test(body) ? body : '');
  const cleanBody = sanitizeEmailHtml(body);
  const combinedText = `${subject} ${cleanBody} ${from}`.slice(0, 25000);
  const textOrderNumber = extractOrderNumberFromText(combinedText);
  const store = resolveStoreName(from, combinedText);
  const lockerPin = extractLockerPin(combinedText);
  const shelfNumber = extractShelfNumber(combinedText);
  const rawPickupLocation = extractPickupLocation(combinedText);
  const redirectInfo = extractRedirectInfo(combinedText);
  const pickupLocation = redirectInfo.newPickupLocation || rawPickupLocation;
  const pickupHours = extractOpeningHours(combinedText);
  const pickupPhone = extractPickupPhone(combinedText);

  const candidatesMap = new Map();

  // 0. Schema.org / JSON-LD Structured Data Extraction (Authoritative Merchant Data)
  const schemaShipments = extractSchemaOrgData(htmlContent);
  let schemaTitle = '';
  let schemaStore = '';
  let schemaStatus = '';

  for (const shipment of schemaShipments) {
    let tn = shipment.trackingNumber;
    let mappedCarrier = mapCarrierNameToId(shipment.carrier);

    if (shipment.trackingUrl) {
      const urlCandidate = extractTrackingFromUrl(shipment.trackingUrl);
      if (urlCandidate) {
        if (!tn) tn = urlCandidate.trackingNumber;
        if (!mappedCarrier || mappedCarrier === 'other') mappedCarrier = urlCandidate.carrier;
      }
    }

    if (tn && !isFalsePositive(tn, combinedText)) {
      const cleanVal = tn.trim().toUpperCase();
      let checksum = 'not-applicable';

      if (!mappedCarrier || mappedCarrier === 'other') {
        for (const rule of COMPILED_RULES) {
          if (rule.re.test(cleanVal)) {
            mappedCarrier = rule.carrierId;
            checksum = evaluateChecksum(cleanVal, rule.checksum);
            break;
          }
        }
      } else {
        const rule = COMPILED_RULES.find((r) => r.carrierId === mappedCarrier && r.re.test(cleanVal));
        if (rule) {
          checksum = evaluateChecksum(cleanVal, rule.checksum);
        }
      }

      if (shipment.title && !schemaTitle) schemaTitle = shipment.title;
      if (shipment.store && !schemaStore) schemaStore = shipment.store;
      if (shipment.status && !schemaStatus) schemaStatus = shipment.status;

      if (!candidatesMap.has(cleanVal)) {
        candidatesMap.set(cleanVal, {
          id: `cand_${candidatesMap.size + 1}`,
          value: cleanVal,
          carrierCandidates: [mappedCarrier || 'other'],
          formatMatch: true,
          checksum,
          urlDomainMatch: Boolean(shipment.trackingUrl),
          schemaOrgMatch: true,
          labelProximity: 1.0,
          falsePositiveFlags: [],
          sourceSpan: { start: 0, end: 0 },
          score: 0.98
        });
      }
    }
  }

  // 1. Courier URL Link Extraction (Highest Priority)
  for (const { carrier, pattern } of CARRIER_URL_PATTERNS) {
    const gPattern = new RegExp(pattern.source, pattern.flags.includes('g') ? pattern.flags : `${pattern.flags}g`);
    let urlMatch;
    while ((urlMatch = gPattern.exec(combinedText)) !== null) {
      const candidateVal = urlMatch[1] || urlMatch[2] || urlMatch[3];
      if (candidateVal && !isFalsePositive(candidateVal, combinedText)) {
        const cleanVal = candidateVal.trim().toUpperCase();
        if (!candidatesMap.has(cleanVal)) {
          candidatesMap.set(cleanVal, {
            id: `cand_${candidatesMap.size + 1}`,
            value: cleanVal,
            carrierCandidates: [carrier],
            formatMatch: true,
            checksum: 'not-applicable',
            urlDomainMatch: true,
            labelProximity: 1.0,
            falsePositiveFlags: [],
            sourceSpan: { start: urlMatch.index || 0, end: (urlMatch.index || 0) + urlMatch[0].length },
            score: 0.95
          });
        }
      }
      if (urlMatch[0].length === 0) {
        gPattern.lastIndex += 1;
      }
    }
  }

  // 2. Scan Labeled Patterns
  const labeledRegex = /(?:tracking\s*(?:number|id|code|no|#)?|מספר\s*מעקב|מס['׳`״’‘]?\s*מעקב|קוד\s*מעקב|דבר\s*דואר(?:\s*שמספרו)?|חבילתך\s*במספר|חבילה\s*מספר|מספר\s*משלוח|waybill|awb|consign(?:ment)?|ברקוד(?:\s*משלוח)?)[\s:=#-]+([A-Za-z0-9_-]{6,35})/gi;
  let labeledMatch;

  while ((labeledMatch = labeledRegex.exec(combinedText)) !== null) {
    const rawVal = labeledMatch[1];
    const cleanVal = rawVal.trim().toUpperCase();
    if (isFalsePositive(cleanVal, combinedText)) continue;

    let matchedCarrier = 'other';
    let checksum = 'not-applicable';

    for (const rule of COMPILED_RULES) {
      if (rule.re.test(cleanVal)) {
        matchedCarrier = rule.carrierId;
        checksum = evaluateChecksum(cleanVal, rule.checksum);
        break;
      }
    }

    const start = labeledMatch.index + labeledMatch[0].indexOf(rawVal);
    const end = start + rawVal.length;

    // Check local proximity window for carrier hints
    const windowStart = Math.max(0, start - 150);
    const windowEnd = Math.min(combinedText.length, end + 150);
    const localContext = combinedText.slice(windowStart, windowEnd).toLowerCase();

    let formatMatch = matchedCarrier !== 'other';

    if (matchedCarrier === 'other') {
      const candidateRule = COMPILED_RULES.find(
        (r) => r.re.test(cleanVal) && localContext.includes(r.carrierId.toLowerCase())
      );
      if (candidateRule) {
        matchedCarrier = candidateRule.carrierId;
        checksum = evaluateChecksum(cleanVal, candidateRule.checksum);
        formatMatch = true;
      } else if (localContext.includes('amazon') || /^TBA\d+/i.test(cleanVal)) {
        matchedCarrier = 'amazon';
        formatMatch = true;
      } else if (/^\d{6,10}$/.test(cleanVal)) {
        if (/chita|cheetah|צ['׳`״]?יטה/i.test(localContext)) { matchedCarrier = 'chita'; formatMatch = true; }
        else if (/hfd|epost|אי-?פוסט/i.test(localContext)) { matchedCarrier = 'hfd'; formatMatch = true; }
        else if (/boxit|בוקסיט/i.test(localContext)) { matchedCarrier = 'boxit'; formatMatch = true; }
        else if (/buzzr|באזר/i.test(localContext)) { matchedCarrier = 'buzzr'; formatMatch = true; }
        else if (/tapuz|תפוז/i.test(localContext)) { matchedCarrier = 'tapuz'; formatMatch = true; }
        else if (/israel\s*post|דואר\s*ישראל/i.test(localContext)) { matchedCarrier = 'israel-post'; formatMatch = true; }
      }
    }

    let score = 0.70;
    if (formatMatch) score += 0.15;
    if (checksum === 'pass') score += 0.15;
    if (checksum === 'fail') score -= 0.10; // modest penalty for placeholder test fixtures
    if (isPromotionalContext(combinedText) && !formatMatch) score -= 0.25;

    if (!candidatesMap.has(cleanVal)) {
      candidatesMap.set(cleanVal, {
        id: `cand_${candidatesMap.size + 1}`,
        value: cleanVal,
        carrierCandidates: [matchedCarrier],
        formatMatch,
        checksum,
        urlDomainMatch: false,
        labelProximity: 1.0,
        falsePositiveFlags: [],
        sourceSpan: { start, end },
        score: Math.min(1.0, Math.max(0.0, score))
      });
    }
  }

  // 3. Scan Tokens against Carrier Rules
  const tokenRegex = /\b([A-Za-z0-9]{6,35})\b/g;
  let tokenMatch;

  while ((tokenMatch = tokenRegex.exec(combinedText)) !== null) {
    const rawVal = tokenMatch[1];
    const cleanVal = rawVal.trim().toUpperCase();
    if (candidatesMap.has(cleanVal) || isFalsePositive(cleanVal, combinedText)) continue;

    for (const rule of COMPILED_RULES) {
      if (rule.re.test(cleanVal)) {
        let checksum = 'not-applicable';
        checksum = evaluateChecksum(cleanVal, rule.checksum);

        // Check proximity if rule is generic digits (e.g. 10 digits for DHL or 12 for FedEx)
        let proximityBoost = 0;
        if (/^\d{10,12}$/.test(cleanVal)) {
          const windowStart = Math.max(0, tokenMatch.index - 120);
          const windowEnd = Math.min(combinedText.length, tokenMatch.index + rawVal.length + 120);
          const localContext = combinedText.slice(windowStart, windowEnd).toLowerCase();
          if (localContext.includes(rule.carrierId.toLowerCase())) {
            proximityBoost = 0.25;
          } else {
            continue; // Skip ambiguous bare digits without carrier keyword nearby
          }
        }

        let score = rule.confidence === 'high' ? 0.70 : 0.45;
        score += proximityBoost;
        if (checksum === 'pass') score += 0.20;
        if (checksum === 'fail') score -= 0.10;

        candidatesMap.set(cleanVal, {
          id: `cand_${candidatesMap.size + 1}`,
          value: cleanVal,
          carrierCandidates: [rule.carrierId],
          formatMatch: true,
          checksum,
          urlDomainMatch: false,
          labelProximity: proximityBoost > 0 ? 0.8 : 0.0,
          falsePositiveFlags: [],
          sourceSpan: { start: tokenMatch.index, end: tokenMatch.index + rawVal.length },
          score: Math.min(1.0, Math.max(0.0, score))
        });
        break;
      }
    }
  }

  const candidates = Array.from(candidatesMap.values()).sort((a, b) => b.score - a.score);
  const selectedCandidate = candidates.length > 0 ? candidates[0] : null;

  let trackingNumber = null;
  let carrier = 'other';
  let status = 'none';
  let confidence = 'none';

  if (selectedCandidate && selectedCandidate.score >= 0.40) {
    trackingNumber = selectedCandidate.value;
    carrier = selectedCandidate.carrierCandidates[0] || 'other';

    if (selectedCandidate.score >= 0.80 && selectedCandidate.checksum !== 'fail') {
      status = 'verified';
      confidence = 'high';
    } else if (selectedCandidate.score >= 0.60) {
      status = 'probable';
      confidence = 'medium';
    } else {
      status = 'uncertain';
      confidence = 'low';
    }
  }

  const effectiveStore = store || schemaStore;
  // Order of preference: what the email's structured data says it is, then
  // what its own contents list says, then whatever can be salvaged from the
  // subject line. The subject is last because it usually names the order, not
  // the thing — "Shipping update for order 469417".
  const itemName = extractShippedItemName(cleanBody);
  const title = schemaTitle
    || (itemName ? (effectiveStore ? `${effectiveStore} - ${itemName}` : itemName) : '')
    || generateCleanTitle(subject, effectiveStore, carrier);
  const latencyMs = Date.now() - startTime;

  const allPackages = [];
  const verifiedCandidates = candidates.filter((c) => (c.score >= 0.80 && c.checksum !== 'fail') || c.schemaOrgMatch);
  const targetCandidates = verifiedCandidates.length > 0
    ? verifiedCandidates
    : (candidates.length > 0 && candidates[0].score >= 0.60 ? [candidates[0]] : []);

  const orderedCandidates = targetCandidates.length > 1
    ? [...targetCandidates].sort((a, b) => (a.sourceSpan?.start ?? 0) - (b.sourceSpan?.start ?? 0))
    : targetCandidates;

  const seenTracking = new Set();
  for (let idx = 0; idx < orderedCandidates.length; idx += 1) {
    const cand = orderedCandidates[idx];
    if (seenTracking.has(cand.value)) continue;
    seenTracking.add(cand.value);

    const tn = cand.value;
    const candCarrier = cand.carrierCandidates[0] || 'other';
    const schemaShipment = schemaShipments.find((s) => s.trackingNumber?.toUpperCase() === tn);

    let candTitle = schemaShipment?.title;
    if (!candTitle) {
      if (targetCandidates.length > 1 && effectiveStore) {
        candTitle = `${effectiveStore} - Shipment #${idx + 1} (${tn.slice(-4)})`;
      } else {
        candTitle = title;
      }
    }

    allPackages.push({
      trackingNumber: tn,
      carrier: candCarrier,
      title: candTitle,
      store: schemaShipment?.store || effectiveStore,
      orderNumber: schemaShipment?.orderNumber || schemaShipments[0]?.orderNumber || textOrderNumber || undefined,
      deliveryStatus: schemaShipment?.status || schemaStatus || undefined,
      pickupLocation: pickupLocation || '',
      pickupHours: pickupHours || undefined,
      pickupPhone: pickupPhone || undefined,
      lockerPin,
      shelfNumber,
      isRedirected: redirectInfo.isRedirected || undefined,
      originalPickupLocation: redirectInfo.originalPickupLocation || undefined,
      redirectReason: redirectInfo.redirectReason || undefined,
      origin: '',
      notes: '',
      status: (cand.score >= 0.80 && cand.checksum !== 'fail') || cand.schemaOrgMatch ? 'verified' : 'probable',
      confidence: (cand.score >= 0.80 && cand.checksum !== 'fail') || cand.schemaOrgMatch ? 'high' : 'medium',
      candidate: cand
    });
  }

  return {
    trackingNumber,
    carrier,
    title,
    store: effectiveStore,
    orderNumber: schemaShipments[0]?.orderNumber || textOrderNumber || undefined,
    deliveryStatus: schemaStatus || undefined,
    pickupLocation: pickupLocation || '',
    pickupHours: pickupHours || undefined,
    pickupPhone: pickupPhone || undefined,
    isRedirected: redirectInfo.isRedirected || undefined,
    originalPickupLocation: redirectInfo.originalPickupLocation || undefined,
    redirectReason: redirectInfo.redirectReason || undefined,
    origin: '',
    notes: '',
    lockerPin,
    shelfNumber,
    status,
    confidence: trackingNumber ? confidence : 'none',
    candidates,
    allPackages,
    selectedCandidate,
    evidenceSummary: selectedCandidate ? [`Selected ${selectedCandidate.value} for ${carrier} (score: ${selectedCandidate.score})`] : [],
    executionPath: selectedCandidate ? 'deterministic_fast_path' : 'safe_abstention',
    latencyMs
  };
}

/**
 * Extracts all verified package tracking details from a message, disaggregating multi-parcel shipments.
 * If multiple parcels are found (e.g. Amazon or AliExpress orders with 2+ tracking numbers), returns an array of all parcels.
 * If no verified tracking numbers are found, returns order status fallback if available, or an empty array.
 *
 * @param {string} subject
 * @param {string} body
 * @param {string} [from]
 * @param {object} [options]
 * @returns {Array<object>}
 */
export function extractAllTrackingDetails(subject = '', body = '', from = '', options = {}) {
  const primary = extractTrackingDetails(subject, body, from, options);
  if (primary.allPackages && primary.allPackages.length > 0) {
    return primary.allPackages;
  }

  const orderStatus = extractOrderStatusDetails(subject, body, from);
  if (orderStatus) {
    return [{
      trackingNumber: '',
      carrier: 'other',
      title: orderStatus.title,
      store: orderStatus.store,
      deliveryStatus: orderStatus.status,
      status: 'none',
      confidence: 'sender_reported',
      isOrderStatusOnly: true
    }];
  }

  return [];
}
